### ISSUE TITLE
creating a thread

### ISSUE THREAD

**Issue by systemd1337** [getgle/getglebbs#1]
creating a thread won't redirect to the thread it just stays on createthread.php

**Comment by getgle** [comment]
I just downloaded the github repo and tried it and it redirects to index.php like its supposed to.   really weird

What version of PHP are you using?

**Comment by systemd1337** [comment]
php 7.1 what is the best way of contacting you besides github?

**Comment by getgle** [comment]
getindor@protonmail.com or Getindor#4411 on discord

**Comment by systemd1337** [comment]
Thank you

**Comment by getgle** [comment]
I checked my server and my local computer.
local computer - php 7.2.24
server php 7.4

It works on both so I'm thinking it's a version difference.  I remember back when I updated to php 7.2 I had to change a bunch of code relating to the json files since they changed the way json_decode works.  I think that is why it doesn't work in older versions of PHP.  I'm sure it probably wouldn't be too hard to mess around with the code so it'd work on PHP 7.1 but as PHP 7.1 is EOL I think it'd be better to just update to the new version of PHP if possible.  

I am going to add in the readme that getglebbs requires php 7.2.  Thank you for telling me about this. 👍
